services:
  web:
    image: "nginx"
    ports:
      - "8000:80"
    networks:
      - my-network
    depends_on:
      - rcache
      - db
  rcache: 
    image: "redis:${TAG}"
    networks:
      - my-network
    depends_on:
      - db
  db: 
    image: "mysql"
    env_file:
      - .env
    networks:
      - my-network
networks:
  my-network:
    driver: bridge